### ISSUE TITLE
Render higher resolutions

### ISSUE THREAD

**Issue by suissemaxx** [ericsujw/InstColorization#1]
First of all – thanks very much for making your code available. Impressive work! Very appreciated.

I tried to render higher resolutions than the default 256 x 256px and changed the argparse variables like so:

```
opt.fineSize = 512
opt.loadSize = 512
```

However, the Colab Pro notebook yields this error:

`RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 15.90 GiB total capacity; 14.61 GiB already allocated; 502.94 MiB free; 14.70 GiB reserved in total by PyTorch)`

How can I fix this or render higher resolutions in another way?

Thanks in advance!

**Comment by ericsujw** [comment]
You can colorize the images using the default resolution, resize the color channel and take original images' L channel to convert back to the full resolution RGB images. (See my last block of the notebook.)

**Comment by suissemaxx** [comment]
Thanks!
