### ISSUE TITLE
How to train with my own dataset?

### ISSUE THREAD

**Issue by matheusdefarias** [ericsujw/InstColorization#11]
Hi! 
I would like to know, how to use the code to train with my own dataset?
Is there a code to run the training step in the repository?

Best regards,

Matheus Santos.

**Comment by matheusdefarias** [comment]
UP!

**Comment by ericsujw** [comment]
Hi!

Please follow this [tutorial](https://github.com/ericsujw/InstColorization/blob/master/README_TRAIN.md) to train our model.

**Comment by matheusdefarias** [comment]
Hey!! Thanks!! 
I will try here :)
Could you tell me if the code runs on Windows? Or just on Linux?

**Comment by ericsujw** [comment]
I only test my code on Ubuntu 18.04.
