### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by boblef** [ericsujw/InstColorization#13]
Is there any way to run the script on a machine that doesn't have GPUs?

**Comment by jerrymatjila** [comment]
Have a look at pull request https://github.com/ericsujw/InstColorization/pull/12
I have tested it by running the example with option ```--gpu_ids -1```
Here is the full command
```code
python test_fusion.py --name test_fusion --sample_p 1.0 --model fusion --test_img_dir example --results_img_dir results --gpu_ids -1
```

**Comment by boblef** [comment]
Thank you!
