### ISSUE TITLE
Fusion Dataset error

### ISSUE THREAD

**Issue by nepersica** [ericsujw/InstColorization#17]
Hi, I have a question about my error.

I just run the train.py for fusion and had a error like this.
" stack expects each tensor to be equal size, but got [2, 3, 256, 256] at entry 0 and [8, 3, 256, 256] at entry 1 "
How can I fix it?

**Comment by nepersica** [comment]
Oh I solve it!:)

**Comment by vztu** [comment]
Hello @nepersica, I have the same problem when training the fusion model:
```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [2, 3, 256, 256] at entry 0 and [1, 3, 256, 256] at entry 1
```
Could you let me know how you solve this problem? Thank you very much!

**Comment by lvchuandong** [comment]
> Hello @nepersica, I have the same problem when training the fusion model:
> 
> ```
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
>     return {key: default_collate([d[key] for d in batch]) for key in elem}
>   File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
>     return {key: default_collate([d[key] for d in batch]) for key in elem}
>   File "/home/ztu/miniconda3/envs/old_photo/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
>     return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [2, 3, 256, 256] at entry 0 and [1, 3, 256, 256] at entry 1
> ```
> 
> Could you let me know how you solve this problem? Thank you very much!
I have the same problem ,did you fix it?
