### ISSUE TITLE
Built error at Ubuntu 18.04.3 LTS,  ERROR: detectron2==0.1.2+cu101

### ISSUE THREAD

**Issue by wangerzi** [ericsujw/InstColorization#3]
Hi, I know this by some technology blog, and this is the best colorization project I have seen

I tried to run it on my personal ubuntu laptop, but I got this problem, I also tried use the docker environment(https://hub.docker.com/r/continuumio/anaconda3) to execute `conda env create --file env.yml --name instacolorization` and got this error as same, can you support me some information about this?

> ['/opt/conda/envs/instacolorization/bin/python', '-m', 'pip', 'install', '-U', '-r', '/opt/InstColorization/condaenv.y2bkp0vm.requirements.txt']
Pip subprocess output:
Collecting absl-py==0.9.0
  Downloading absl-py-0.9.0.tar.gz (104 kB)
Collecting cachetools==4.1.0
  Downloading cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> 
> Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement detectron2==0.1.2+cu101 (from -r /opt/InstColorization/condaenv.y2bkp0vm.requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for detectron2==0.1.2+cu101 (from -r /opt/InstColorization/condaenv.y2bkp0vm.requirements.txt (line 4))
>
>
>CondaEnvException: Pip failed

Thanks.

**Comment by onefish51** [comment]
me too

**Comment by ericsujw** [comment]
Hi @onefish51 , @wangerzi 
I've moved out some of the package from env.yml. Please follow my README.md for a new installation process.

**Comment by wangerzi** [comment]
Thanks for response, I already run it~Alough my GPU memory is not enough.../(ㄒoㄒ)/~~
