### ISSUE TITLE
How to trian the model?

### ISSUE THREAD

**Issue by iamxinxin** [ericsujw/InstColorization#5]
Great work! And thanks for sharing the code. 
 I tried to combine another colorization method to this segmentation-colorization-fusion framework on a ubuntu computer with a GTX1080Ti GPU, but I'm confused that I did not find the file for training these models in your repo. 
Could  you share how you trained the models?

**Comment by iamxinxin** [comment]
@ericsujw @jbhuang0604 #5 
Hi， sorry to disturb again. 
I want to complete the codes needed to train your work and combine the fusion model with my image synthesis algorithm.
I have read your paper and codes carefully with reference to the relevant colorization-pytorch repository,

However, I am still not sure about training FusionGenerator and WeightGenerator. 
The SIGGRAPHGenerator and InstanceGenerator can be trained with reference to the colorization-pytorch repository. 
Are these loss and parameter update functions also applicable to FusionGenerator and WeightGenerator models without any change?
In addition, do you plan to expose the code related to training the model? 
Any response from you is greatly appreciated！！

**Comment by ericsujw** [comment]
Hi!

Please follow this [tutorial](https://github.com/ericsujw/InstColorization/blob/master/README_TRAIN.md) to train our model.

**Comment by iamxinxin** [comment]
Thanks
